### ISSUE TITLE
某些情况下CBLoopScaleHelper.getCurrentItem这个方法会报空指针

### ISSUE THREAD

**Issue by Ice-Liu** [Bigkoo/Android-ConvenientBanner#241]
java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.ViewGroup$LayoutParams android.view.View.getLayoutParams()' on a null object reference
        at android.support.v7.widget.RecyclerView$LayoutManager.getPosition(RecyclerView.java:8294)
        at cn.zero.android.common.view.banner.helper.CBLoopScaleHelper.getCurrentItem(CBLoopScaleHelper.java:133)
        at cn.zero.android.common.view.banner.ConvenientBanner$AdSwitchTask.run(ConvenientBanner.java:267)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:171)
        at android.app.ActivityThread.main(ActivityThread.java:6684)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:246)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)

**Comment by saiwu-bigkoo** [comment]
会不会是调用时机不对，比如还没渲染完成你就去getCurrentItem 了

**Comment by Ice-Liu** [comment]
我本身的项目代码里没有调用过getCurrentItem这个方法

**Comment by saiwu-bigkoo** [comment]
我这重现不了，某些情况是具体什么情况。按源码判断是：垂直，横向同时不可滚动会为null，子控件数量为0会为null。

**Comment by TooCMS-AIHP** [comment]
我这的操作是跳页再返回一直重复这个操作几次之后在当前页等待他自动轮播  这个时候有可能会出现view为null的情况   您试一下

**Comment by saiwu-bigkoo** [comment]
会不会是跳转了却忘记关掉轮播
 // 开始自动翻页
    @Override
    protected void onResume() {
        super.onResume();
//        //开始自动翻页
        convenientBanner.startTurning();
    }

    // 停止自动翻页
    @Override
    protected void onPause() {
        super.onPause();
//        //停止翻页
        convenientBanner.stopTurning();
    }
这个没绑定

**Comment by TooCMS-AIHP** [comment]
@Override
    public void onResume() {
        super.onResume();
        banner.startTurning(5000);
    }

    @Override
    public void onPause() {
        super.onPause();
        banner.stopTurning();
    }

我的代码是这样的，如果没有参数的话好像是不会自动轮播

**Comment by saiwu-bigkoo** [comment]
因为我在xml里面配置了参数。你这样其实也是一样的。

**Comment by TooCMS-AIHP** [comment]
对  我觉得这样是没有问题  但是就是偶尔会出现空指针异常

public int getCurrentItem() {
        View view = mLinearSnapHelper.findSnapView(mRecyclerView.getLayoutManager());
        if (view != null) {
            return mRecyclerView.getLayoutManager().getPosition(view);
        }
        return 0;
    }

我现在已经把getCurrentItem方法改成这样了  判了个空 否则返回0
