### ISSUE TITLE
报空指针

### ISSUE THREAD

**Issue by lihuanming** [Bigkoo/Android-ConvenientBanner#258]
E/AndroidRuntime: FATAL EXCEPTION: main
        Process: com.langsi.meicool, PID: 8907
        java.lang.NullPointerException: Attempt to invoke virtual method 'android.support.v7.widget.RecyclerView$LayoutManager com.bigkoo.convenientbanner.view.CBLoopViewPager.getLayoutManager()' on a null object reference
        at com.bigkoo.convenientbanner.helper.CBLoopScaleHelper.getCurrentItem(CBLoopScaleHelper.java:127)
        at com.bigkoo.convenientbanner.ConvenientBanner$AdSwitchTask.run(ConvenientBanner.java:303)
        at android.os.Handler.handleCallback(Handler.java:761)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:156)
        at android.app.ActivityThread.main(ActivityThread.java:6523)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)

**Comment by saiwu-bigkoo** [comment]
会不会是你重写了setLayoutmanager然后return null呢

**Comment by wadewen** [comment]
我的也是这里报空指针，当没有数据的时候，你的解决了吗

**Comment by saiwu-bigkoo** [comment]
没数据的时候是吗？我测试一下

**Comment by saiwu-bigkoo** [comment]
我这也没测出问题，2.1.4我捕获了异常。你们看看行不行吧

**Comment by wadewen** [comment]
升级到2.1.4后不会直接崩溃了
