### ISSUE TITLE
一直报空指针，虽然没有崩溃

### ISSUE THREAD

**Issue by liangfengxixi** [Bigkoo/Android-ConvenientBanner#266]
06-12 11:07:44.069 12827-12827/com.ctc.itv.yueme.debug W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'android.support.v7.widget.RecyclerView$LayoutManager com.bigkoo.convenientbanner.view.CBLoopViewPager.getLayoutManager()' on a null object reference
06-12 11:07:44.070 12827-12827/com.ctc.itv.yueme.debug W/System.err:     at com.bigkoo.convenientbanner.helper.CBLoopScaleHelper.getCurrentItem(CBLoopScaleHelper.java:129)
        at com.bigkoo.convenientbanner.ConvenientBanner$AdSwitchTask.run(ConvenientBanner.java:304)
        at android.os.Handler.handleCallback(Handler.java:743)
06-12 11:07:44.071 12827-12827/com.ctc.itv.yueme.debug W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:150)
        at android.app.ActivityThread.main(ActivityThread.java:5621)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)

**Comment by liangfengxixi** [comment]
2.1.4版本，运行Demo却没发现这个，神奇

**Comment by twlk-jzy** [comment]
我也报了  有解决吗？
