### ISSUE TITLE
划着划着就崩了, 经常这样

### ISSUE THREAD

**Issue by LZLuzhuo** [Bigkoo/Android-ConvenientBanner#297]
如题:

    java.lang.IndexOutOfBoundsException: Invalid index 6, size is 5
        at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
        at java.util.ArrayList.get(ArrayList.java:308)
        at com.bigkoo.convenientbanner.listener.CBPageChangeListener.onPageSelected(CBPageChangeListener.java:31)
        at com.bigkoo.convenientbanner.helper.CBLoopScaleHelper$1.onScrollStateChanged(CBLoopScaleHelper.java:55)
        at android.support.v7.widget.RecyclerView.dispatchOnScrollStateChanged(RecyclerView.java:4881)
        at android.support.v7.widget.RecyclerView.setScrollState(RecyclerView.java:1467)
        at android.support.v7.widget.RecyclerView$ViewFlinger.smoothScrollBy(RecyclerView.java:5133)
        at android.support.v7.widget.RecyclerView$SmoothScroller$Action.runIfNecessary(RecyclerView.java:11665)
        at android.support.v7.widget.RecyclerView$SmoothScroller.onAnimation(RecyclerView.java:11472)
        at android.support.v7.widget.RecyclerView$SmoothScroller.access$600(RecyclerView.java:11341)
        at android.support.v7.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:5045)
        at android.os.Handler.handleCallback(Handler.java:808)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:5409)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:859)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:675)
        at dalvik.system.NativeStart.main(Native Method)

**Comment by LZLuzhuo** [comment]
布局是这样的:
convenientbanner 放在 RecyclerView 的头部, RecyclerView 放在 ViewPager 里
正常放没事, 如果把翻几页ViewPager, 再翻回来, 然后继续翻 convenientbanner , 一会儿就索引越界崩掉了

**Comment by LZLuzhuo** [comment]
把 ViewPager 翻来翻去, 即使不去翻 convenientbanner , 也崩掉了
ViewPager 有3页, convenientbanner 设置了自动播放,
觉得这可能跟ViewPager 的缓存机制有关

    java.lang.IndexOutOfBoundsException: Invalid index 9, size is 5
        at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
        at java.util.ArrayList.get(ArrayList.java:308)
        at com.bigkoo.convenientbanner.listener.CBPageChangeListener.onPageSelected(CBPageChangeListener.java:31)
        at com.bigkoo.convenientbanner.helper.CBLoopScaleHelper$1.onScrollStateChanged(CBLoopScaleHelper.java:55)
        at android.support.v7.widget.RecyclerView.dispatchOnScrollStateChanged(RecyclerView.java:4881)
        at android.support.v7.widget.RecyclerView.setScrollState(RecyclerView.java:1467)
        at android.support.v7.widget.RecyclerView$ViewFlinger.smoothScrollBy(RecyclerView.java:5133)
        at android.support.v7.widget.RecyclerView$SmoothScroller$Action.runIfNecessary(RecyclerView.java:11665)
        at android.support.v7.widget.RecyclerView$SmoothScroller.onAnimation(RecyclerView.java:11472)
        at android.support.v7.widget.RecyclerView$SmoothScroller.access$600(RecyclerView.java:11341)
        at android.support.v7.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:5045)
        at android.os.Handler.handleCallback(Handler.java:808)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:5409)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:859)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:675)
        at dalvik.system.NativeStart.main(Native Method)

**Comment by LZLuzhuo** [comment]
确实跟 ViewPager  的缓存有关
